name: Deploy to Vercel on Main

on:
  push:
    branches:
      - main

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel Deploy Hook
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_yPKkTY0IY9WcRTXKmwSV30pMILFP/l8yjzT4I3w
